//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pczimmet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAtikPc
    {
        public int atikID { get; set; }
        public string atikAdi { get; set; }
        public int atikAdedi { get; set; }
        public string atikMarka { get; set; }
        public string atikModel { get; set; }
        public string atikOzellik { get; set; }
        public Nullable<int> satinalmaID { get; set; }
    
        public virtual tblPcStok tblPcStok { get; set; }
    }
}
