//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pczimmet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPcStok
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPcStok()
        {
            this.tblAtikPc = new HashSet<tblAtikPc>();
            this.tblZimmet = new HashSet<tblZimmet>();
        }
    
        public int satinalmaID { get; set; }
        public string satinalmaParcaAdi { get; set; }
        public System.DateTime satinalmaTarihi { get; set; }
        public decimal satinalmaFiyati { get; set; }
        public string satinalmaMarka { get; set; }
        public string satinalmaModel { get; set; }
        public string satinalmaOzellik { get; set; }
        public byte satinalmaAdet { get; set; }
        public int satinalmaTuru { get; set; }
        public int tedarikciID { get; set; }
        public bool zimmetDurumu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAtikPc> tblAtikPc { get; set; }
        public virtual tblTedarikci tblTedarikci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblZimmet> tblZimmet { get; set; }
    }
}
