//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pczimmet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTedarikci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTedarikci()
        {
            this.tblPcStok = new HashSet<tblPcStok>();
        }
    
        public int tedarikciID { get; set; }
        public string tedarikciAdi { get; set; }
        public string tedarikciAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPcStok> tblPcStok { get; set; }
    }
}
