//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pczimmet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZimmet
    {
        public int zimmetID { get; set; }
        public int personelID { get; set; }
        public int satinalmaID { get; set; }
        public int zimmetAdet { get; set; }
    
        public virtual tblPcStok tblPcStok { get; set; }
        public virtual tblPersonel tblPersonel { get; set; }
    }
}
